version: 2
updates:
  - package-ecosystem: npm
    directory: /bruno
    schedule:
      interval: weekly
    labels: [dependencies]
  - package-ecosystem: npm
    directory: /playwright/typescript
    schedule:
      interval: weekly
    labels: [dependencies]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [dependencies]
